# Конфигурация библиотеки анализа текста визуальных новелл

# Конфигурация вывода результатов
output:
  output_dir: "analysis"  # Директория для сохранения результатов анализа
  metrics_file: "metrics.txt"  # Имя файла для сохранения метрик

# Конфигурация моделей и устройств
model:
  use_gpu: true  # Использовать ли GPU, если доступен
  device_id: 0  # Идентификатор GPU устройства (если их несколько)
  sentiment_model: "cointegrated/rubert-tiny-sentiment-balanced"  # Модель для анализа настроений
  embedding_model: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"  # Модель для эмбеддингов

# Общие параметры анализа
analyse:
  max_clusters: 20  # Максимальное количество кластеров для анализа
  min_topics: 2  # Минимальное количество тем для моделирования
  max_topics: 20  # Максимальное количество тем для моделирования
  reading_speed_wpm: 150.0  # Скорость чтения в словах в минуту

# Конфигурация анализа персонажей
character:
  predefined_names: 
    - "авия"
    - "альберт"
    - "амар"
    - "рейн"
    - "валл"
    - "аркадий"
    - "бадд"
    - "брайан"
    - "вал"
    - "виктория"
    - "владимир"
    - "все"
    - "ганс"
    - "генрих"
    - "голос из рации"
    - "гриша"
    - "джек"
    - "джим"
    - "джон"
    - "другая часть"
    - "есико"
    - "жан"
    - "женщина-диктор"
    - "инженер"
    - "класс"
    - "кот кпк"
    - "кто-то в классе"
    - "кэролин"
    - "линда"
    - "лука"
    - "маргарет"
    - "медик"
    - "неизвестная фигура"
    - "несколько учеников"
    - "одна часть класса"
    - "официант"
    - "работник"
    - "радриго"
    - "рейн"
    - "робот уборщик"
    - "сара"
    - "саша"
    - "софия"
    - "софья"
    - "судья"
    - "тина"
    - "тихон"
    - "ученик 2"
    - "ученик 3"
    - "ученик 4"
    - "ученик 6"
    - "ученица 5"
    - "фигура 1"
    - "фигура 2"
    - "фигура, озаренная светом"
    - "филипп"
    - "хусейн"
    - "эльвира"
    - "ява"
    - "ян"

# Конфигурация энкодера эмбеддингов
embedding:
  module_path: null  # Полный путь к пользовательскому классу обработчика (например, "your_module.YourEmbeddingProcessor")

# Конфигурация парсера текста
parser:
  module_path: null  # Полный путь к пользовательскому классу парсера (например, "your_module.YourParserClass")
  args:
    character_name_uppercase: true  # Считать строку в верхнем регистре именем персонажа
    ignore_html_comments: true  # Игнорировать HTML-комментарии
    exclude_frequent_words_count: 30  # Количество наиболее частых слов для исключения

# Конфигурация анализа настроений
sentiment:
  module_path: null  # Полный путь к пользовательскому классу обработчика (например, "your_module.YourSentimentProcessor")
  args:
    split_chunk_max_length: 512  # Максимальная длина чанка при разделении текста
    split_chunk_overlap: 50  # Количество перекрывающихся токенов между чанками

# Прямая конфигурация порогов и перцентилей для анализа настроений
sentiment_analyze_config:
  positive_threshold: 0.05  # Порог для определения положительного настроения
  negative_threshold: -0.05  # Порог для определения отрицательного настроения
  sentiment_percentile_lower: 5  # Нижний перцентиль для фильтрации выбросов
  sentiment_percentile_upper: 95  # Верхний перцентиль для фильтрации выбросов

# Конфигурация тематического моделирования
topic:
  top_words_count: 7  # Количество топ-слов для каждой темы
  num_topics_defaults: 5  # Число тем по умолчанию
  max_df_vectorizer: 1.0  # Максимальная частота документа для векторизатора
  # Перцентили для фильтрации тем
  topic_percentile_lower: 10
  topic_percentile_upper: 90

# Конфигурация кластеризации
clustering:
  inertia_threshold: 0.1  # Пороговое значение для определения оптимального числа кластеров
  pca_components: 2  # Количество компонентов для PCA
  tsne_components: 2  # Количество компонентов для t-SNE
  # Перцентили для фильтрации кластеров
  cluster_percentile_lower: 5
  cluster_percentile_upper: 95
  perplexity: 30  # Параметр perplexity для t-SNE

# Конфигурация анализа повторяемости
repetition:
  high_repetition_threshold: 0.7  # Высокий порог повторяемости
  medium_repetition_threshold: 0.5  # Средний порог повторяемости
  top_words_limit: 30  # Максимальное количество топ-слов для анализа
  top_chart_words: 10  # Количество слов для отображения на графике
  # Перцентили для фильтрации данных о повторяемости
  repetition_percentile_lower: 5
  repetition_percentile_upper: 95

# Конфигурация анализа нарратива
narrative:
  block_percentile_lower: 5  # Нижний процентиль для фильтрации блоков
  block_percentile_upper: 95  # Верхний процентиль для фильтрации блоков
  sentence_min_length: 3  # Минимальная длина предложения (в словах)
  dynamic_rhythm_threshold: 5  # Порог для определения динамичного ритма
  moderate_rhythm_threshold: 3  # Порог для определения умеренного ритма

# Конфигурация статистического анализа
statistics:
  iqr_factor: 0.4  # Множитель для межквартильного размаха
  significance_threshold: 0.05  # Порог значимости для статистических тестов
  filter_percentile_lower: 5  # Нижний процентиль для фильтрации выбросов
  filter_percentile_upper: 95  # Верхний процентиль для фильтрации выбросов
  cosine_similarity_threshold: 0.7  # Порог косинусной близости
  
  # Перцентили для статистических вычислений
  quartile_first: 25  # Первый квартиль (Q1)
  quartile_third: 75  # Третий квартиль (Q3)
  significant_value_percentile: 40  # Перцентиль для определения значимых значений
  outlier_iqr_multiplier: 1.5  # Множитель IQR для выбросов
  
  # Бины и гистограммы
  sturges_offset: 1  # Смещение для правила Стёрджесса
  friedman_diaconis_factor: 2  # Фактор для правила Фридмана-Диаконса
  histogram_bins_min: 5  # Минимальное количество бинов для гистограммы
  histogram_bins_max: 50  # Максимальное количество бинов для гистограммы
